### ISSUE TITLE
`sdssplitargs` should lazily create the string instead of pushing 1 by 1 into the new one.

### ISSUE THREAD

**Issue by hbina** [EQ-Alpha/KeyDB#248]
https://github.com/JohnSully/KeyDB/blob/69a74a567bd381a84e71f954d4cb35eb878f6d3c/src/sds.c#L998

Was just browsing the codebase and noticed that this string arguments splitting function is eagerly creating the vector of argument substrings by calling `sdscatlen` at pretty much every non-whitespace character. This could potentially allocate multiple times for long arguments.

I think it should just iterate through the arguments, remember when it started and just allocate as required.

According to this: https://github.com/JohnSully/KeyDB/blob/69a74a567bd381a84e71f954d4cb35eb878f6d3c/src/sds.c#L236
The allocated buffer is multiplied by 2 each time, which assumes that strings are usually around the power of 2; which is not true I think.

I don't think Redis made any changes to this.

https://github.com/redis/redis/blob/8b497881f2eda5b028cc2ba0aa17ef204f6a083b/src/sds.c#L979

**Comment by christianEQ** [comment]
I spent some time looking into this, and I don't think there's a valuable change to be made. It parses one character at a time so it can add escape characters, quoted sections, etc. While the logic could of course be rewritten I don't think there's sufficient reason to do so. As for the allocation, the fact that it doubles every time doesn't mean it assumes strings are around the power of 2, it simply assumes that the string doubling in length is an approximately reasonable ceiling. Common implementations of C++'s `std::vector<T>::resize` use this same paradigm. In any case, performance is negligibly affected by the handful of reallocations that happen while reading each token.

Closing since there's no user-affecting improvement to be made.
