### ISSUE TITLE
How active-replica ensure data consistency

### ISSUE THREAD

**Issue by yongman** [EQ-Alpha/KeyDB#307]
I am wonder how the active-replica ensure the key consistency if the same key being written in each replica at the same time.

I reviewed the code of replication and found mvcc mechanism can not ensure this feature, if yes correct me.

Anyone have some suggestions? Or should we avoid writing same key at the same time in client?

**Comment by VivekSainiEQ** [comment]
Hi @yongman,

I'm curious as to what you mean by key consistency. If you're referring to strong consistency, then yes, the MVCC mechanism is not sufficient to guarantee this. We would need a different protocol (such as RAFT which we're working on internally) in order to achieve strong consistency. However if you're referring to consistency in general, MVCC timestamps help to ensure that eventually all the nodes will have the same key values. If a key were to be written by multiple clients at once, the data from the latest write would eventually be replicated across the network.
