### ISSUE TITLE
Repercussions of replicaof self ?

### ISSUE THREAD

**Issue by gnat** [EQ-Alpha/KeyDB#326]
Let's say I have this config file on host 10.0.0.1

```
port 6379
requirepass mypassword123
masterauth mypassword123
multi-master yes
active-replica yes
replicaof 10.0.0.1 6379
replicaof 10.0.0.2 6379
replicaof 10.0.0.3 6379
```

Note: A replicaof entry exists for the current host (10.0.0.1)

The advantage here is it vastly simplifies configuration, but are there any negative long term unforeseen consequences of this?

Thanks!

**Comment by gnat** [comment]
@JohnSully Any quick insight on whether this is safe to do? :smiley:

**Comment by VivekSainiEQ** [comment]
Hi @gnat,

By setting a server to be a replica of itself, the server will act as both the sender and recipient of replication traffic. This shouldn't cause a crash or data corruption or anything of the sort, however you may incur a performance penalty due to the added traffic. So in summary, yes it's safe, but you're better off not replicating from self.
