### ISSUE TITLE
Do we have capability to ignore waiting for response from Pipeline?

### ISSUE THREAD

**Issue by fferozbasha** [EQ-Alpha/KeyDB#330]
In some situations, where the commands in a pipeline is only with 'Updates/Delete's, am actually not interested in the response unless there are any error's. In that case, do we have a way to instruct the pipeline to ignore waiting for response and proceed further?. Tried the 'CLIENT NO REPLY" option, but it still blocking.

**Comment by JohnSully** [comment]
Hi @fferozbasha I'm not sure I understand the situation.  When you issue commands in a pipeline they will be completed sequentially and the results added to the clients send buffer.  We do not wait for the result to be transmitted before moving to the next command.  However if we spend too long processing a client we may move on to another in order to ensure fairness (we will eventually get back and complete servicing of the pipeline).

Are you specifically using a blocking command like blpop?

**Comment by fferozbasha** [comment]
@JohnSully Thanks for the response. Let me put an example. Consider I have created a pipeline with 100 hmset commands. Now with Python client, the code will be as ,
response = pipe.execute()
...next line of code

Now in this scenario, am not interested in the response at all. I understand the the client collects all request and send at once to the server. But post that it is going to get all response and send it back to the client. Only then the 'next line of code' gets executed. I do not want the code to wait for the response back from the server. Just like fire and forget approach. Do you think it is a reasonable ask?

**Comment by JohnSully** [comment]
Hi @fferozbasha 

There's nothing in KeyDB that forces you to wait for a response before continuing. Unfortunately this is an issue with the library you are using and you'll need to get the modifications there.  If your client is waiting for data to be returned from KeyDB to continue then there isn't a way around it on the server side, e.g. if we didn't send a response at all then your client would just hang.
