### ISSUE TITLE
[BUG] Building on Raspberry 4 fails

### ISSUE THREAD

**Issue by Talkabout** [EQ-Alpha/KeyDB#336]
**Describe the bug**

Build on Raspberry Pi 4 fails with following error:

```
    CC adlist.o
    CC quicklist.o
    CC ae.o
    CC anet.o
    CC dict.o
    CC server.o
In file included from server.cpp:31:
server.h:857:35: error: static assertion failed: object size is critical, don't increase
 static_assert(sizeof(redisObject) == 16, "object size is critical, don't increase");
               ~~~~~~~~~~~~~~~~~~~~^~~~~
make[1]: *** [Makefile:392: server.o] Fehler 1
make[1]: Verzeichnis „/home/xxx/keydb/src“ wird verlassen
make: *** [Makefile:6: all] Fehler 2
```

**To reproduce**

Try to build on a Raspberry Pi 4 :)

**Expected behavior**

Build should run without error

**Additional information**

**Comment by Talkabout** [comment]
Hi,

seems to be related to this:

https://github.com/EQ-Alpha/KeyDB/issues/240

putting "<=" instead of "==" makes building possible again.

Bye

**Comment by Talkabout** [comment]
Hi,

after building and starting I was facing major memory/cpu issues. I have 2 nodes with active-replica configured and a database of 250+ MBs. Both nodes were consuming 100% cpu (2 processes), no other applications were able to set keys because of error (redis is loading data file into memory). At some point the kernel killed keydb because of memory overflow. Not sure what exactly has been done but for my environment it is not working at all. Rollback to 6.0.16 and everyhing is working smoothly again. If any further information is required to track this down, please ask.

Bye

**Comment by BobEQAlpha** [comment]
Do you have the memory overflow during or after `the redis is loading data file into memory`?

If it's during, I recommend you still enable `active-replica`, try to have the first node only replicate from the second. Then when full synchronization is complete, then have the second node replicate from the first. This way, we can see if the issue is for one of the nodes or both of the nodes only.

If it's after, what is the maximum number of concurrent clients do you have for the 2 nodes?
