### ISSUE TITLE
Install Issue on RHEL7 VM

### ISSUE THREAD

**Issue by server2245** [EQ-Alpha/KeyDB#379]
I was trying to build KeyDB 6.2.1 on RHEL7 VM which has GCC-C++ 4.8.5 but got below error while running MAKE command

g++: error: unrecognized command line option ‘-std=c++14’

What's the minimum OS version supported by KeyDB ?

**Comment by VivekSainiEQ** [comment]
Hi @server2245,

In order to use the `-std=c++14` flag, you need at least GCC-C++ 5.2.0, so I suppose that's the minimum version required.

Alternatively, you can modify the Makefile (under the src/ directory) and change the flag to `-std=c++1y`, then run `make distclean; make` from the command line. That may allow KeyDB to compile, but I would recommend upgrading GCC to a suitable version if you are able to.
