### ISSUE TITLE
[BUG] Cannot set client-output-buffer-limit as argument to the keydb-server

### ISSUE THREAD

**Issue by Antiarchitect** [EQ-Alpha/KeyDB#380]
**Describe the bug**

Cannot set client-output-buffer-limit as argument to the keydb-server:
https://github.com/Enapter/charts/issues/37

**To reproduce**

```
docker run --rm -it eqalpha/keydb:x86_64_v6.2.1 keydb-server --client-output-buffer-limit "normal 0 0 0"

*** FATAL CONFIG FILE ERROR (KeyDB 6.2.1) ***
Reading the configuration file, at line 2
>>> 'client-output-buffer-limit "normal 0 0 0"'
Bad directive or wrong number of arguments
```

**Expected behavior**

The argument is treated like a config directive.

**Comment by aland-zhang** [comment]
keydb Reading the configuration file, at line 1588                                                                                                                                                   │
│ keydb >>> 'client-output-buffer-limit "normal 0 0 0 replica 0 0 0 pubsub 128mb 64mb 60"'                                                                                                             │
│ keydb Bad directive or wrong number of arguments

**Comment by VivekSainiEQ** [comment]
Hi @Antiarchitect,

The client-output-buffer-limit parameter takes in 3 arguments, however you seem to be passing in only one (which is the entire string `normal 0 0 0`). The following command should work, note the lack of quotation marks:

```
docker run --rm -it eqalpha/keydb:x86_64_v6.2.1 keydb-server --client-output-buffer-limit normal 0 0 0
```

In addition, when setting different types of client-output-buffer-limit (normal, replica, pubsub), you need to do those one per line instead of all at once. So instead of:
```
... --client-output-buffer-limit normal 0 0 0 replica 0 0 0 pubsub 128mb 64mb 60
```
It would be:
```
... --client-output-buffer-limit normal 0 0 0 --client-output-buffer-limit replica 0 0 0 --client-output-buffer-limit pubsub 128mb 64mb 60
```
Hope this helps.

**Comment by Antiarchitect** [comment]
@VivekSainiEQ Thank you. Looks horrible but I'll try to do something about that in my helm chart.
