### ISSUE TITLE
Massive amount of "idle" traffic for KeyDB master-master replication?

### ISSUE THREAD

**Issue by ministry-of-code** [EQ-Alpha/KeyDB#382]
Hello KeyDB Team,

we switched from a Redis master-slave replication on three servers to KeyDB master-master replication some days ago. It was a "drop in" replacement - we kept the redis.conf in general and just added some config options to enable master-master replication. Technically everything works perfectly, but I got an alarm from our monitoring system a couple of hours later. The idle traffic on the intenal database network went up from between 10-20 MBit/sec to a constant >40MBit/sec.

So my question is: is this "by design"? Can I consider this as a normal behavior for a KeyDB master-master replication setup with 3 machines? Will this idle traffic become even more when I add machines to the cluster?

Would be great if someone could give me an insight.

![2021-12-02 11_11_45-Observium - Brave](https://user-images.githubusercontent.com/2571417/145348789-5b564c87-b82b-438a-a565-e3556dfa926b.png)

**Comment by VivekSainiEQ** [comment]
Hi @ministry-of-code,

Sorry for the delayed response. Yes, this is by design as each master propagates each command it receives (that it hasn't seen before) to all of the masters it's connected to, which leads to increased traffic. Yes, this will become more pronounced as you add machines to the cluster. You can look at the `multi-master-no-forward` configuration if you wish to reduce network traffic, but doing so can be very dangerous and lead to data loss.
