### ISSUE TITLE
Association with fastonosql

### ISSUE THREAD

**Issue by Ontopic** [EQ-Alpha/KeyDB#394]
What exactly is the reason https://fastonosql.com/ is being featured as a recommended tool? Seems like a very shady "open source" construction with aggressive chatbot implementation from yesteryear as though I'm shopping for a Wordpress theme. I was about to drop Redis, but this is giving me serious doubts...

**Comment by Ontopic** [comment]
Don't get me wrong; I don't mind paying for a pro version with a clear advantage an separation of concerns between the community and enterprise edition, but this is wrong...

**Comment by Ontopic** [comment]
If there is not association; why are they the only option listed? Is KeyDB in reality not that compliant with existing ecosystem of KeyDB?

**Comment by Ontopic** [comment]
Because I would be happier with an honest; "yeah, we own Redis, but we have no GUI's really".

**Comment by benschermel** [comment]
We do not currently own any GUIs and do not have immediate plans to make one. fastonosql included explicit support for KeyDB which is why they were referenced here.

I understand how this could be misinterpreted RE GUI support across KeyDB and would like to clarify that KeyDB remains compatible with the Redis API, protocol & modules. This means any existing GUIs compatible with Redis will also work with KeyDB. However note that if you are using KeyDB specific features (subkey expires, active-rep, etc) that the library may not contain support for those. 

I updated the readme section as it included some stale links as well. 

I would like to mention we will be making documentation specific to GUI use and will also include a section specifically regarding community maintained projects that support KeyDB as more have popped up and we appreciate all contributors.

**Comment by JohnSully** [comment]
Fasto was an early adopter of KeyDB and as always we are happy for community support.  I was unaware of the direction the project took since then, we should review all of our recommendations to ensure they are still suitable.

**Comment by VivekSainiEQ** [comment]
References to fastonosql look to be removed, closing this thread.
