### ISSUE TITLE
Active Replication CRDTs supported types

### ISSUE THREAD

**Issue by vladimir-stornest** [EQ-Alpha/KeyDB#395]
I plan to use KeyDB on my project with Active Replication, but I read comments that CRDT is not implemented yet for advanced data types.

I couldn't find in the documentation what data types and operations are safe to use with active replication.

I use sorted sets, lists, and the INCR/DECR operations in my project. Is CRDT implemented for these types?

**Comment by benschermel** [comment]
Hi @vladimir-stornest, CRDTs are not implemented for all data types yet, and specifically those associated with your request. Because this uses a last-write-wins methodology the more recent value will take precedent when it comes to things like INCR/DECR for competing writes. For lists they may become unordered as data is replayed.

**Comment by benschermel** [comment]
Closing issue and opening new issue for updating documentation surrounding supported data structures in KeyDB Docs repo.
