### ISSUE TITLE
How about make WAIT works like ACID serializable transaction in CockroachDB for Active-Active?

### ISSUE THREAD

**Issue by moredure** [EQ-Alpha/KeyDB#98]

**Comment by JohnSully** [comment]
If I'm understanding correctly what you would like is the ability to hide transactions from other clients until a WAIT completes successfully.  This makes sense and is definitely something I will implement and support.  We are already planning transaction rollbacks so it's a very natural fit.

Instead of modifying WAIT I will most likely add an argument to the EXEC command to provide this stronger guarantee.

**Comment by mikefaraponov** [comment]
My use case was ACID state management across datacenters for long running tasks (started,completed,failed).

But, I solved it without such behavior for WAIT, using queueing and ACID state management in place where task is running, not where task was initiated (datacenters)
